#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0

# This conf script is capable of backing up
db_capb backup

# State machine
# See http://www.fifi.org/doc/debconf-doc/tutorial.html#AEN217
STATE=1
while [ "$STATE" != 0 -a "$STATE" != 4 ]; do
    case "$STATE" in
    1)
        # Mysql ROOT password
        db_input critical appliance-manager/mysql-root-password || true
    ;;
    
    2)
        # OSA password
        db_input critical appliance-manager/mysql-osa-password || true
    ;;
    
    3)
        # Admin password
        db_input critical appliance-manager/admin-new-password || true
    ;;
    
    *)
        # Do nothing, behing here should never happen
        exit 10
    ;;
    esac

    if db_go; then
        STATE=$(($STATE + 1))
    else
        STATE=$(($STATE - 1))
    fi
done

if [ $STATE -eq 0 ]; then
    # The user has asked to back up from the first
    # question. This case is problematical. Regular
    # dpkg and apt package installation isn’t capable
    # of backing up questions between packages as this
    # is written, so this will exit leaving the package
    # unconfigured - probably the best way to handle
    # the situation.
    exit 10
fi
