 $.datepicker.regional['fr'] = {clearText: 'Effacer', clearStatus: '',
    closeText: 'Fermer', 
    closeStatus: 'Fermer sans modifier',
    prevText: '<Préc',
    prevStatus: 'Voir le mois précédent',
    nextText: 'Suiv>',
    nextStatus: 'Voir le mois suivant',
    currentText: 'Aujourd\'hui', 
    currentStatus: 'Voir le mois courant',
    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin',
    'Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
    monthNamesShort: ['Jan','Fév','Mar','Avr','Mai','Jun',
    'Jul','Aoû','Sep','Oct','Nov','Déc'],
    monthStatus: 'Voir un autre mois', 
    yearStatus: 'Voir un autre année',
    weekHeader: 'Sm', 
    weekStatus: '',
    dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
    dayNamesShort: ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'],
    dayNamesMin: ['Di','Lu','Ma','Me','Je','Ve','Sa'],
    dayStatus: 'Utiliser DD comme premier jour de la semaine', 
    dateStatus: 'Choisir le DD, MM d',
    dateFormat: 'dd/mm/yy', 
    firstDay: 0, 
    initStatus: 'Choisir la date', 
    isRTL: false,
 };
 $.timepicker.regional['fr'] = {clearText: 'Effacer', clearStatus: '',
    closeText: 'Fermer', 
    closeStatus: 'Fermer sans modifier',
    prevText: '<Préc',
    prevStatus: 'Voir le mois précédent',
    nextText: 'Suiv>',
    nextStatus: 'Voir le mois suivant',
    currentText: 'Maintenant', 
    currentStatus: 'Voir le mois courant',
    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin',
    'Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
    monthNamesShort: ['Jan','Fév','Mar','Avr','Mai','Jun',
    'Jul','Aoû','Sep','Oct','Nov','Déc'],
    monthStatus: 'Voir un autre mois', 
    yearStatus: 'Voir un autre année',
    weekHeader: 'Sm', 
    weekStatus: '',
    dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
    dayNamesShort: ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'],
    dayNamesMin: ['Di','Lu','Ma','Me','Je','Ve','Sa'],
    dayStatus: 'Utiliser DD comme premier jour de la semaine', 
    dateStatus: 'Choisir le DD, MM d',
    dateFormat: 'dd/mm/yy', 
    firstDay: 0, 
    initStatus: 'Choisir la date', 
    isRTL: false,
	ampm: false,
	amNames: ['AM', 'A'],
	pmNames: ['PM', 'P'],
	timeFormat: 'hh:mm tt',
	timeSuffix: '',
	timeOnlyTitle: 'Choisir l\'heure',
	timeText: 'Heure',
	hourText: 'Heure',
	minuteText: 'Minute',
	secondText: 'Seconde',
	millisecText: 'Milliseconde',
	timezoneText: 'Time Zone',
 };
 $.datepicker.setDefaults($.datepicker.regional['fr']);
 $.timepicker.setDefaults($.timepicker.regional['fr']);
 
