#!/bin/bash
# Call the closure compiler to minify js. 
# Takes a filename myjs.x.y.js and outputs myjs.x.y.min.js, a minified version.

# The location of the closure compiler jar. You'll probably need to edit this.
CLOSURE_COMPILER=./compiler.jar

case "$1" in
""|"-h"|"--help")
    echo "Usage: minifyjs path/to/js/file.js"
    exit 1;
    ;;
esac

jsDir=`dirname $1`
jsFile=`basename $1`

# There's no way to get "from the beginning to the Nth to last field" when
# specifying a range via cut, but we can get "from the Nth field to the end".
# By reversing the string, cutting, and reversing back, we get the desired
# effect. The following gets myfile.min.js from myfile.js
minjsFile=`echo $jsFile | rev | cut -d"." -f2- | rev`.min.js

jsFilePath=$jsDir/$jsFile
minjsFilePath=$jsDir/min/$minjsFile


java -jar $CLOSURE_COMPILER --js=$jsFilePath --js_output_file=$minjsFilePath
echo "$jsFilePath minified. Now located at $minjsFilePath"
